### ISSUE TITLE
Publish library in Maven Central

### ISSUE THREAD

**Issue by javagl** [javagl/bh-tsne#1]
Upon agreement with the original author, this library is supposed to be published in Maven Central.

**Comment by javagl** [comment]
@lejon I invited you as a collaborator to this (currently private) repo, in order to discuss whether it is OK to make it public, and publish the resulting library in Maven Central.

**Comment by javagl** [comment]
@lejon Despite repeated attempts, there has been no feedback regarding this issue, so the repository is now public, and the library is available in Maven Central.

**Comment by lejon** [comment]
Excellent! Good job! Sorry for lagging on this!
